### ISSUE TITLE
Simply, merging of 3 devices (2 Android) (1 Windows) on the Android Phone my bookmarks are gone ... 

### ISSUE THREAD

**Issue by fcelsie** [AntonyCorbett/JWLMerge#87] opened 2023-01-08 14:41 UTC
**Describe the bug**

**To Reproduce**
3. See error

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - Windows version
 - Other important information about your environment

**Comment by fcelsie** [comment] 2023-01-08 14:43
Windows and Tablet have no issue Samsung S22 ultra will not update bookmarks, but instead removes them completely.  Thanks

**Comment by AntonyCorbett** [comment] 2023-01-08 17:13
@fcelsie I assume that you are attempting to import the same merged backup into 3 devices and that 2 of the devices (a Windows PC and a tablet) successfully import the backup with bookmarks intact, whereas a third device - the Samsung S22 ultra - imports the backup but leaves the bookmarks empty. This could be caused by corruption in the JWL data held on the Samsung device. One way to check is to remove the data (or JWL itself) from the Samsung S22 and then import the merged backup. Please let me know what you find.

**Comment by fcelsie** [comment] 2023-01-08 17:15
Thank you for your quick reply. I'll give that a try.

Fred Celsie
Lake Nona
Orlando FL 32832

________________________________

**Comment by fcelsie** [comment] 2023-01-22 14:00
Just a follow up.  It seems to have stopped working again … It will not successfully merge everything.  I can get my underlining but I lose my Bible bookmarks every time on my cell phone. I tried taking one of the devices out of the equation, tried unchecking bookmarks on the Surface, but no go … I’m stuck on this one …  Thanks for any help you may have, I’ve used this for years without a hitch, it’s weird 😉 Fred  Fred CelsieLake NonaOrlando FL 32832Mobile – (407) 494-5103 From: Antony CorbettSent: Sunday, January 8, 2023 12:13 PMTo: AntonyCorbett/JWLMergeCc: fcelsie; MentionSubject: Re: [AntonyCorbett/JWLMerge] Simply, merging of 3 devices (2 Android) (1 Windows) on the Android Phone my bookmarks are gone ... (Issue ***@***.*** I assume that you are attempting to import the same merged backup into 3 devices and that 2 of the devices (a Windows PC and a tablet) successfully import the backup with bookmarks intact, whereas a third device - the Samsung S22 ultra - imports the backup but leaves the bookmarks empty. This could be caused by corruption in the JWL data held on the Samsung device. One way to check is to remove the data (or JWL itself) from the Samsung S22 and then import the merged backup. Please let me know what you find.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

**Comment by AntonyCorbett** [comment] 2023-01-22 14:46
@fcelsie I assume it is the same Bible on both devices. If so, the best way to investigate this further is if you send me 2 backup files that when merged and imported into your cell phone produce the problem you describe (i.e. an empty bookmark list for the Bible). I can then merge the files and examine what may be going wrong. You can send to antony@corbetts.org.uk

**Comment by AntonyCorbett** [comment] 2023-02-16 17:42
This thread continued by email. @fcelsie - did you see my emails of 30 Jan requesting an example of a bookmark in one of the backup files that you sent me that fails to transfer correctly?

**Comment by fcelsie** [comment] 2023-02-16 18:18
I did, but it's been a particularly busy time. I may not get to this until
the weekend. I'll follow up. Sorry for the delay.

Fred



Fred Celsie
Lake Nona
Orlando, Fl 32832
Mobile - (407) 494-5103

**Comment by AntonyCorbett** [comment] 2023-02-19 17:42
Closing now after a discussion with @fcelsie.

**Closed by AntonyCorbett** 2023-02-19 17:42 UTC

**Comment by fcelsie** [comment] 2023-02-19 17:45
Awesome, thanks!

Fred Celsie
Lake Nona
Orlando, Fl 32832
Mobile - (407) 494-5103

**Comment by AurelienKun** [comment] 2023-02-19 18:42
@fcelsie you should modify your answer that contain personnal info from your mail signature. 
@AntonyCorbett thanks for your amazing work. Very useful ! ;-)

**Comment by AntonyCorbett** [comment] 2023-02-19 18:45
> you should modify your answer

@AurelienKun thanks - I have done this for @fcelsie
