### ISSUE TITLE
JW Library 11.5 issue

### ISSUE THREAD

**Issue by thesim81** [AntonyCorbett/JWLMerge#25] opened 2020-04-10 08:59 UTC
328/5000
The files generated by the new version of JW Library (11.5) are not loaded into the program. The files generated by the previous version (11.4.2) work correctly. The problem may be caused by the fact that 2 new colors of highlighters have been added in the new version.
Sorry for my bad English
Thank you!

**Comment by AntonyCorbett** [comment] 2020-04-10 10:20
@thesim81 Thanks. I am looking at it now. The database version has changed which means JWLMerge doesn't even attempt to load the backup files. I am investigating what changes have been made to the database schema.

**Comment by AntonyCorbett** [comment] 2020-04-10 10:49
@thesim81 There are some changes to the schema to support the rolling playback and shuffle of media  and these affect the user "Tabs" table. I'll need to take a look at some sample data files before making the fix.

**Comment by thesim81** [comment] 2020-04-10 12:04
Ok, thank you so much for your work

**Comment by AntonyCorbett** [comment] 2020-04-10 17:54
@thesim81 Please see latest pre-release. There are significant changes so some tested needed please!

**Comment by thesim81** [comment] 2020-04-10 18:22
Installed the new version, it correctly recognizes the two files that I pass to it, but when I press "merge" it doesn't save any file, the folder is empty. I'm on windows 10 64bit, I haven't received any errors.
![2020-04-10 201925](https://user-images.githubusercontent.com/59028958/79013404-f5455b80-7b68-11ea-8d25-2ada18589f80.png)

[log-20200410.txt](https://github.com/AntonyCorbett/JWLMerge/files/4462853/log-20200410.txt)

**Comment by thesim81** [comment] 2020-04-10 18:35
I did some tests and found the problem, if both "tags" are selected it doesn't work. Setting how in the screenshot works correctly.
![2020-04-10 202814](https://user-images.githubusercontent.com/59028958/79013968-2eca9680-7b6a-11ea-8f4b-9048dcaed2df.png)

**Comment by AntonyCorbett** [comment] 2020-04-11 09:21
@thesim81 Is it possoble to send me a link to the 2 backup files please? If you want to post them here you can maintain privacy by removing notes - load the backup into JWLMerge and then use the "Redact Notes" command in the Details page.

**Comment by thesim81** [comment] 2020-04-11 11:10
ok

[UserdataBackup.zip](https://github.com/AntonyCorbett/JWLMerge/files/4464494/UserdataBackup.zip)

**Comment by thesim81** [comment] 2020-04-11 11:11
> 
> 
> @thesim81 Is it possoble to send me a link to the 2 backup files please? If you want to post them here you can maintain privacy by removing notes - load the backup into JWLMerge and then use the "Redact Notes" command in the Details page.

Yes.
[UserdataBackup.zip](https://github.com/AntonyCorbett/JWLMerge/files/4464496/UserdataBackup.zip)

**Comment by AntonyCorbett** [comment] 2020-04-11 11:39
@thesim81 Thanks - I received the files

**Comment by AntonyCorbett** [comment] 2020-04-11 12:15
@thesim81 I have update the latest pre-release. It works on the data files you sent but would welcome further testing.

**Comment by thesim81** [comment] 2020-04-11 12:48
> 
> 
> @thesim81 I have update the latest pre-release. It works on the data files you sent but would welcome further testing.

Yes, work fine! thank you! I've test with other files too.. all work

**Comment by pacoweiss** [comment] 2020-04-12 08:34
> > @thesim81 I have update the latest pre-release. It works on the data files you sent but would welcome further testing.
> 
> Yes, work fine! thank you! I've test with other files too.. all work

@Thank you so much @AntonyCorbett for your timely support. We us JWLibrary extensively here at the Congo branch. I have tested the Prerelease 1.1.02 with pre 11.5 backups as well as 11.5 backups both from Windows and Android platform. It seems to work well, I can merge both versions together. Thanks for all your help.

**Comment by DarkLordGMS** [comment] 2020-04-17 16:24
> > > @thesim81 I have update the latest pre-release. It works on the data files you sent but would welcome further testing.
> > 
> > 
> > Yes, work fine! thank you! I've test with other files too.. all work
> 
> @thank you so much @AntonyCorbett for your timely support. We use JWLMerge extensively here at the Congo branch. I have tested the Prerelease 1.1.0.2 with pre 11.5 backups as well as 11.5 backups both from Windows and Android platform. It seems to work well, I can merge both versions together. Thanks for all your help.

Sadly this is no longer possible with the latest version. Do you still have the pre release 1.1.0.2?

I tried opening a pre 11.5 backup with the latest release (1.1.0.4) and it doesn't open it.

**Comment by DarkLordGMS** [comment] 2020-04-18 15:34
@thesim81 @pacoweiss Does any of you have the pre-release file? Version 1.1.0.2. The current release file doesn't open older files, only 11.5 files.

**Comment by pacoweiss** [comment] 2020-04-18 15:37
> @thesim81 @pacoweiss Does any of you have the pre-release file? Version 1.1.0.2. The current release file doesn't open older files, only 11.5 files.

You don't need a prerelease, since JWLibrary can basically convert the versions for you. I tried it for several brothers and it works well:
1.	Back-up you current version of JWLibrary into a new file.
2.	Restore an old back-up file into JWLibrary.
3.	Create a new back-up file with the data just imported.
4.	Repeat step 2 and 3 for each ‘old’ back-up file that needs to be ‘upgraded’ into the new database format so it can again be merged
5.	Restore the back-up file created in step 1
6.	All back-up files that were update during steps 2-4 can now be merged as usual with JWLMerge 1.1.0.4

**Comment by DarkLordGMS** [comment] 2020-04-18 15:40
That's not what I'm trying to do. I'm trying to merge a 11.5 file with a previous version file using Jwlmerge because I can't use version 11.5  because it keeps force closing. That's why I was wondering if you have the pre release 1.1.0.2 because that one can open old backup files and new ones

**Comment by DarkLordGMS** [comment] 2020-04-18 15:43
The purpose is to try to convert a 11.5 version backup file into an older version backup file because the latest version of JW Library that doesn't force close is version 11.4.2 and that one doesn't allow restoring 11.5 backup files because of the v7 database update that was implemented on version 11.5

**Comment by pacoweiss** [comment] 2020-04-18 15:47
Is the forced closing linked to the database file, or to another problem in JWLibrary? I could open all pre 11.5 JWL backups without problem in JWL 11.5. But here in Congo, with slow Internet, a new installation of JWL often forces closing when the catalogue file is not fully downloaded.
Keeping JWL open on the start page, without clicking on any publication, would normally do the trick (here in Congo, it may take up to several hours to download the full catalog). Manually deleting the catalog file in the app folder is sometimes needed if it gets corrupted. Just an idea.

**Comment by DarkLordGMS** [comment] 2020-04-18 15:51
No, the force closing is not related to the database update. It force closes every time I open a publication. I've tried everything but doesn't work. That's why I had to roll back. It's an issue with just these two tablets I'm troubleshooting. They're really old but it's all these brothers can afford. 

Yeah, I can open all 11.5 backup files with JW Library 11.5. But can't open 11.5 backup files with older JW Library versions like 11.4.2.

**Comment by DarkLordGMS** [comment] 2020-04-18 16:10
So basically they're stuck on using JW Library version 11.4.2. But they never did any backups. I'm the one who made the backup on version 11.5. That's why I want to try to convert that file into an older version to be able to restore it with JW Library version 11.4.2

**Comment by AntonyCorbett** [comment] 2020-04-19 06:34
@DarkLordGMS JWLMerge can only load backups from a single JWL database version and there is no code to upgrade or downgrade a backup file to another version.

**Comment by pacoweiss** [comment] 2020-04-19 12:00
@DarkLordGMS We had the exact same behavior as you described above (JWL crashes as soon as you open/click on any publication), but it was catalog related. The problem disappeared after having left JWL open for some time without clicking on anything. Due to Internet limitations here, we had to leave it open for a few hours (best results with device connected to power and leaving JWL open over night). We solved at least 20 cases like this, with the same symptom as you describe.  And in Congo, the brother typically have older devices... Our JW Helpdesk here at the branch gave out the same direction to brothers calling. You may want to give it a try .... ? It may be that your problem is different, but trying it does not cost anything.

**Comment by pacoweiss** [comment] 2020-04-25 17:04
@DarkLordGMS, I hope the problem is solved on your side. If not, please install the latest version of JWL that addresses exactly that problem:
_Fixed an issue where the app would crash when turning Bluetooth on and off, or when restarting the device
Fixed an issue on some Android 5.x devices where the app would crash opening the Daily Text, Meetings tab, or any publication_
With this fix, you should be able to use the latest JWL installation to 'upgrade' the backup files to the latest DB version and then use JWL Merge as needed.

**Closed** 2020-06-14 17:21 UTC
Labels: enhancement
