### ISSUE TITLE
Lost underlining and bookmarks in merge between JWL Apps on Windows and Android

### ISSUE THREAD

**Issue by ck--** [AntonyCorbett/JWLMerge#39] opened 2021-03-04 19:04 UTC
**Describe the bug**
When merging between Windows and Android, following things are lost:
* underlining in the *Pure Worship* book
* bookmarks in the Bible

**Configuration of the merge**
![image](https://user-images.githubusercontent.com/4234401/110015955-c4dc5200-7d24-11eb-812c-e6042c930717.png)

**Expected behavior**
Until recently the underlining have been merged too.

**Version information**
 - JWL App Windows version: 12.3.114
 - JWL App Android version: 12.3.2
 - The publication *Pure Worship* is up-to-date on both platforms

**Comment by AntonyCorbett** [comment] 2021-03-04 20:55
@ck-- Thanks for the report. I can't reproduce the issue, but would be happy to investigate further if you can provide the 2 backup files. You can email them to me if you want. jwmerge@corbetts.org.uk

**Comment by ck--** [comment] 2021-03-05 06:13
@AntonyCorbett Thanks for answering. Just sent you the files.

**Comment by ck--** [comment] 2021-03-05 20:19
Here are screenshots of the problems.

### Underlining

Missing Underlines on Windows after merge:

> ![JLW App Windows Missing unelinings Screenshot 2021-03-05 204435](https://user-images.githubusercontent.com/4234401/110168929-31745100-7df8-11eb-9aba-ce8b5783af41.jpg)


Missing Underlines on Android after merge:

> ![Screenshot_20210305-204325](https://user-images.githubusercontent.com/4234401/110169047-6385b300-7df8-11eb-8ffd-f381300ec315.jpg)

### Bookmarks

Correct Bible Bookmarks on Windows before and after merge:

> ![JLW App Windows Bible bookmarks Screenshot 2021-03-05 204435](https://user-images.githubusercontent.com/4234401/110168362-5e743400-7df7-11eb-81a1-1a71763ce703.jpg)

Missing Bible Bookmarks on Android after merge:

> ![JWL App Android Merged Bible bookmarks missing Screenshot_20210305-203949](https://user-images.githubusercontent.com/4234401/110168812-012cb280-7df8-11eb-9e76-8868e6f24fc1.jpg)

**Comment by AntonyCorbett** [comment] 2021-03-05 21:18
@ck-- Consider the first screenshot showing no highlighting in para 17 of the publication. I reset the data in JWL and then imported the Windows backup - there was no highlighting for para 17. I then reset the data again and restored the Android backup - again there was no highlighting in para 17. This obviously explains why there is no highlighting in the merged file. It looks like the backup files themselves may not contain the data you think they do. If you can provide a precise set of instructions that clearly shows the issue then I will investigate further, but at the moment it looks like the merge operation is working properly.

**Comment by ck--** [comment] 2021-03-06 07:00
@AntonyCorbett this sounds like the JWL App itself does incorrect backups.
I added the underlines on Android at paras 17ff and then started the backup. So on Android the must be in the file. This is very strange

**Comment by AntonyCorbett** [comment] 2021-03-06 07:37
@ck-- it could be that the database on your android device is corrupt. I'll close the issue, but please let me know if you find out more.

**Closed by AntonyCorbett** 2021-03-06 07:37 UTC
Labels: question

**Comment by ck--** [comment] 2021-03-07 06:19
@AntonyCorbett How can I find that out whether it is corrupt?
How can that happen? I have iteratively and weekly merged data from 2 and then 3 devices for at least 6 iterations. Could that have caused the corruption?

**Comment by ck--** [comment] 2021-03-07 06:58
@AntonyCorbett Could you please also have a look whether in UserDataBackup_2021-03-04_CK-SURPRO.jwlibrary para 16 has correct underlines? Or can you tell me how I can find out myself?

**Comment by AntonyCorbett** [comment] 2021-03-07 09:37
@ck-- The JWL database is not particularly resilient to crashes and doesn't have comprehensive integrity constraints, so it is prone to corruption. However, the usual symptom is that JWL won't load or crashes regularly.

**Comment by AntonyCorbett** [comment] 2021-03-07 09:37
@ck-- You can tell what is in your backup file by resetting your data on Windows (Uninstall Programs => JWL => Advanced => Reset) and then importing the backup file.

**Comment by AntonyCorbett** [comment] 2021-03-07 15:13
@ck-- Further to the above, there's an interesting article on the SQLite website regarding database corruption: https://www.sqlite.org/howtocorrupt.html
